# Generated by Django 5.0.6 on 2025-12-12 06:27

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('owners', models.CharField(blank=True, max_length=500)),
                ('date', models.DateField()),
                ('content', models.TextField()),
                ('project_category', models.TextField(choices=[('Design Engineering', 'Design Engineering'), ('Data Analysis', 'Data Analysis'), ('Process Optimization', 'Process Optimization')], max_length=300)),
                ('featured_image', models.URLField(blank=True, null=True)),
                ('gallery_image', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=256, null=True)),
                ('last_name', models.CharField(blank=True, max_length=256, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=256, null=True)),
                ('verification_code', models.CharField(blank=True, max_length=10, null=True)),
                ('is_password_changed', models.BooleanField(default=False)),
                ('kyc_status', models.CharField(default='unverified', help_text='unverified, verified, pending', max_length=20)),
                ('is_activated', models.BooleanField(default=False)),
                ('profile_photo', models.CharField(default='', max_length=300)),
                ('gender', models.CharField(blank=True, default='male', max_length=245, null=True)),
                ('status', models.CharField(blank=True, default='pending', max_length=256, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('Designation', models.CharField(blank=True, max_length=50, null=True)),
                ('is_superadmin', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('admin_role', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('fcm_token', models.CharField(blank=True, max_length=256, null=True)),
                ('admin_auth_code', models.IntegerField(blank=True, null=True)),
                ('admin_auth_code_expiry', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
