# Generated by Django 5.0.6 on 2025-12-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_category',
            field=models.TextField(choices=[('Design Engineering', 'Design Engineering'), ('Data Analysis', 'Data Analysis'), ('Process Optimization', 'Process Optimization')], default='Design Engineering', max_length=300),
        ),
    ]
