# Generated by Django 5.0.6 on 2025-12-24 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 12, 24, 12, 33, 46, 107212)),
        ),
    ]
