# Generated by Django 5.0.6 on 2025-12-24 12:01

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_alter_project_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('authors', models.CharField(blank=True, max_length=500)),
                ('abstract', models.TextField(blank=True)),
                ('full_text', models.TextField(blank=True)),
                ('research_type', models.CharField(choices=[('article', 'Research Article'), ('paper', 'Research Paper'), ('publication', 'Publication'), ('conference', 'Conference Paper'), ('thesis', 'Thesis/Dissertation')], default='article', max_length=20)),
                ('journal_name', models.CharField(blank=True, max_length=255)),
                ('conference_name', models.CharField(blank=True, max_length=255)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('doi', models.CharField(blank=True, max_length=100, verbose_name='DOI')),
                ('publication_date', models.DateField(default=datetime.datetime.now)),
                ('volume', models.CharField(blank=True, max_length=50)),
                ('issue', models.CharField(blank=True, max_length=50)),
                ('pages', models.CharField(blank=True, max_length=50)),
                ('url', models.URLField(blank=True, verbose_name='Research URL')),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated keywords')),
                ('thumbnail_image', models.URLField(blank=True, null=True)),
                ('featured_image', models.URLField(blank=True, null=True)),
                ('pdf_file', models.URLField(blank=True, null=True, verbose_name='PDF File URL')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('views_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Research',
                'ordering': ['-publication_date', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 12, 24, 13, 1, 36, 300570)),
        ),
    ]
