# Generated by Django 5.0.6 on 2025-12-24 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_research_alter_project_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 12, 24, 13, 20, 27, 395652)),
        ),
        migrations.AlterField(
            model_name='research',
            name='publication_date',
            field=models.DateField(default=datetime.datetime(2025, 12, 24, 13, 20, 27, 396594)),
        ),
    ]
